version: 2.1

references:
  sbt_image: &sbt_image
               # Please make sure to sync the SBT (build.properties) and Scala versions (build.sbt)
               hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3

jobs:
  test:
    docker:
      - image: *sbt_image
    parameters:
      sbt-project-folder:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-dependencies-{{ checksum "<< parameters.sbt-project-folder >>/build.sbt" }}
      - run:
          name: Compile and Test Units
          command: |
            cd << parameters.sbt-project-folder >>
            sbt -no-colors -batch "; compile; test"
      - save_cache:
          key: sbt-dependencies-{{ checksum "<< parameters.sbt-project-folder >>/build.sbt" }}
          paths:
            - ~/.m2
            - ~/.ivy2

workflows:
  version: 2

  # This workflow is executed for PR branches
  test_branch:
    jobs:
      - test:
          matrix:
            parameters:
              sbt-project-folder:
                - publishing-service
                - importer-service
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore: /.*/