version: 2.1

references:
  sbt_image: &sbt_image
               hseeberger/scala-sbt:graalvm-ce-20.3.0-java11_1.4.5_2.13.4

jobs:
  test:
    docker:
      - image: *sbt_image
    parameters:
      sbt-project-folder:
        type: string
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-dependencies-{{ checksum "<< parameters.sbt-project-folder >>/build.sbt" }}
      - run:
          name: Compile and Test Units
          command: |
            cd << parameters.sbt-project-folder >>
            sbt -no-colors -batch "; compile; test"
      - save_cache:
          key: sbt-dependencies-{{ checksum "<< parameters.sbt-project-folder >>/build.sbt" }}
          paths:
            - ~/.m2
            - ~/.ivy2

workflows:
  version: 2

  # This workflow is executed for PR branches
  test_branch:
    jobs:
      - test:
          sbt-project-folder: publishing-service
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore: /.*/